name: ci

on: [ push, pull_request ]

jobs:
  flake-and-bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8 . --max-line-length=101
      - name: Check cyclomatic complexity
        run: |
          poetry run flake8 --max-complexity=10 .
      - name: Run bandit
        run: |
          poetry run bandit -r .
#          TODO: add tests execution
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
