name: ci

on: [ push, pull_request ]

jobs:
  flake-and-bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8 . --max-line-length=101
      - name: Check cyclomatic complexity
        run: |
          poetry run flake8 --max-complexity=10 .
      - name: Run bandit
        run: |
          poetry run bandit -r .
