name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt update -y && \
          sudo apt install -y sqlcipher libsqlcipher-dev && \
          python -m pip install --upgrade pip && \
          pip install poetry && \
          poetry install
      - name: Lint with flake8
        run: poetry run flake8 . --max-line-length=101
      - name: Check cyclomatic complexity
        run: poetry run flake8 --max-complexity=10 --max-line-length=101 .

  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt update -y && \
          sudo apt install -y sqlcipher libsqlcipher-dev && \
          python -m pip install --upgrade pip && \
          pip install poetry && \
          poetry install
      - name: Run Tests
        run: poetry run pytest --cov . --cov-branch --cov-report=term --cov-fail-under=60
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt update -y && \
          sudo apt install -y sqlcipher libsqlcipher-dev && \
          python -m pip install --upgrade pip && \
          pip install poetry && \
          poetry install
      - name: Run bandit
        run: poetry run bandit -r .

  selenium:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        firefox: [ '84.0', 'devedition-84.0b1', 'latest-beta', 'latest-devedition', 'latest-nightly', 'latest-esr', 'latest' ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest
            - run: |
                echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
                ${{ steps.setup-firefox.outputs.firefox-path }} --version

      - name: Install dependencies
        run: |
          sudo apt update -y && \
          sudo apt install -y sqlcipher libsqlcipher-dev && \
          python -m pip install --upgrade pip && \
          pip install poetry && \
          poetry install

      - name: Run Selenium tests with Poetry
        run: |
          poetry run pytest test/ui/ui.py
